# Generated by Django 4.2 on 2023-05-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.director')),
            ],
        ),
    ]
