# Generated by Django 4.2 on 2023-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=128)),
                ('last', models.CharField(blank=True, max_length=128, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='actors', to='films.film')),
            ],
        ),
    ]
