# Generated by Django 4.2 on 2023-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
